version: 2

sphinx:
  configuration: _doc/conf.py

formats: [epub, pdf]

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
  - method: pip
    path: . 
    extra_requirements: [docs]
