version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - pip install ryd>=0.8.2
      - ryd convert --generate-mkdocs-config mkdocs.yaml _doc

python:
  install:
  - method: pip
    path: .
    extra_requirements: [docs]

mkdocs:
  configuration: mkdocs.yaml
